### ISSUE TITLE
Hands and body not showing

### ISSUE THREAD

**Issue by eszn** [TheNexusAvenger/Nexus-VR-Character-Model#1]
My hands(controllers) aren't showing. The selecting for teleport movement is also misaligned. HELP!

**Comment by TheNexusAvenger** [comment]
Can you be more specific? Can you provide screenshots and a test game, as well as the headset you are using?

**Comment by TheNexusAvenger** [comment]
Closing this issue due to a lack of information. Make sure the game you own that you are adding the Nexus VR Character Model is set up correctly.

**Comment by eszn** [comment]
fixed
