### ISSUE TITLE
Legs have object collision but arms have no collision

### ISSUE THREAD

**Issue by TimeToCry** [TheNexusAvenger/Nexus-VR-Character-Model#14]
what would I have to do to make the arms collide with certain objects in the game?
I'm using a quest 2 to test out my game.

**Comment by TheNexusAvenger** [comment]
Nexus VR Character Model does not affect these properties of the character. This would be a generic question on how to make arms collide with an R15 character, VR or not. Scripting Support on the developer forum would be a better place to ask.
