### ISSUE TITLE
Cannot interact with UI

### ISSUE THREAD

**Issue by ghost** [TheNexusAvenger/Nexus-VR-Character-Model#15]
I can open the menu but I cannot interact with anything in the menu.

**Comment by TheNexusAvenger** [comment]
Which menu are you referencing? If this is the Nexus VR Character Model menu, can you post a screenshot that shows the pointing setting? If this is the Roblox menu, that is up to Roblox to maintain and there is nothing I can fix.

**Comment by ghost** [comment]
I cannot send a screenshot, but I believe the Roblox UI is blocking the Nexus UI.

**Comment by TheNexusAvenger** [comment]
I haven't experienced this issue and the idea of overlapping UI sounds like a limitation of the Roblox VR pointers and whatever game this is happening in. This may not be reasonably fixable on my end.

**Comment by ghost** [comment]
Alright.
