### ISSUE TITLE
When you set LocalCharacterTransparency = 0, The script freaks out and stops working correctly.

### ISSUE THREAD

**Issue by Funrollercoaster606** [TheNexusAvenger/Nexus-VR-Character-Model#18]
When setting LocalCharacterTransparency to zero, First Person will not work. Only Third Person works. 
Im trying to make a game called Roblox VRlab, and its not working correctly. If you could add seperate character transparency settings, i could work around the issue. Heres the code.

My script:
--script
Appearance = {
        --Transparency of the character when in first person.
        LocalCharacterTransparency = 0,

        --If true, arms will be allowed to disconnect.
        --Recommended to be true locally so that the controllers match the hands,
        --and false for other players so that arms appear normal.
        LocalAllowArmDisconnection = true,
        NonLocalAllowArmDisconnection = true,

        --Maximum angle the neck can turn before the torso turns.
        MaxNeckRotation = math.rad(35),
        MaxNeckSeatedRotation = math.rad(60),

        --Maximum angle the neck can tilt before the torso tilts.
        MaxNeckTilt = math.rad(60),

        --Maximum angle the center of the torso can bend.
        MaxTorsoBend = math.rad(10),
    },

**Comment by TheNexusAvenger** [comment]
I'm not sure I understand the issue. The expected behavior is transparency will be 0 when in first person. What do you get instead? Can you post a screenshot?

**Comment by Funrollercoaster606** [comment]
Instead, i get a third person mode, and able to see the character's hats, but not its body. The point of it is supposed to be kind of like SteamVR's Aperture Hand Lab hands. In that sense, its supposed to make all of the body transparent, but not the hand models, which are welded onto the character and placed into the startercharacter. The same with the hat.

**Comment by Funrollercoaster606** [comment]
Also, it would be handy to have seperate transparency for each object. LowerLeftArm, LowerRightArm, etc. Is this possible?

**Comment by Funrollercoaster606** [comment]
Also, another example is kind of like Rec-Room, but without the torso part.

**Comment by Funrollercoaster606** [comment]
Also, how to make it so you can grab a tool, but then when you release it drops?

**Comment by Funrollercoaster606** [comment]
Nevermind. I added a texture to the character (which was 0) and it fixed. Thanks for helping, though!
