### ISSUE TITLE
Multiple Quest 2 users reporting issues playing in VR after update to 2.6.0

### ISSUE THREAD

**Issue by ControlCoreAngel** [TheNexusAvenger/Nexus-VR-Character-Model#21]
While I'm 90% sure this is just a case of multiple user errors, we have now had 3 back-to-back reports of users on Quest being unable to play in VR. I have asked the relevant questions regarding if they have SteamVR open (usually this is enough for Roblox to recognize that you are in VR), but all appear to be taking the correct steps to join the game in VR mode. I haven't heard anything else from non-Quest users and have yet to test on my own headset to confirm the issue. This seems to be a new development after we upgraded to 2.6.0 trying to fix the black screen glitch (which was still occurring and may still be, but I have yet to hear reports of it).

Roblox launches in VR mode but doesn't properly make the player their character. 
[https://media.discordapp.net/attachments/1100856513003782215/1100891059678101535/image.png?width=845&height=475](url)

Am in the process of getting more information: please let me know what you need and I'll ask my community.

**Comment by TheNexusAvenger** [comment]
A view of the F9 debug window may provide some clues to what is going on. If I were to take a guess, it may be character-specific.

**Comment by ControlCoreAngel** [comment]
Finally got a player to send me console screenshots. Here they are.

https://media.discordapp.net/attachments/1100856513003782215/1100926318205468722/Capture_decran_2023-04-21_020114.png

https://media.discordapp.net/attachments/1100856513003782215/1100926318557810748/Capture_decran_2023-04-27_012454.png

https://media.discordapp.net/attachments/1100856513003782215/1100926318897532948/Capture_decran_2023-04-27_012522.png

**Comment by TheNexusAvenger** [comment]
In screenshot 1, there is a script named "NVR Pointing" that attempts to use a resource in Nexus VR Core that was removed.

**Comment by ControlCoreAngel** [comment]
Unsure if my old pointing script is the problem due to this being platform-specific to Quest 2 users.

Removed and (still) waiting for more console logs from players...
agony

Will update you when I get either confirmation VR works again or when I get console logs.

**Comment by ControlCoreAngel** [comment]
Update: bug still occurring after VRPointing script removed, no errors output in console.

**Comment by TheNexusAvenger** [comment]
There isn't obviously wrong that I can see. I have nothing else I can think of trying.

**Comment by ControlCoreAngel** [comment]
Think this was an issue on our end- the NexusVRCharacterModelClientLoader script wasn't enabled and I didn't find it till now. Dunno if this WAS the problem, but I imagine it was.
Apologies for the inconvenience!

**Comment by TheNexusAvenger** [comment]
Huh... sounds like your game doesn't use the main version of Nexus VR Character Model that gets automatically loaded in. Using a static version isn't really supported.

**Comment by ControlCoreAngel** [comment]
Fixed issue, it was exactly the thing I mentioned with NexusVRCharacterModelClientLoader being disabled. Sorry!

Sadly I'm too unfamiliar with Rojo to do the automatic versions, so when I need to update I just download from here.

**Comment by TheNexusAvenger** [comment]
[Nexus VR Character Model's loader](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/NexusVRCharacterModelLoader.server.lua) is a standalone script that loads in the latest version. This was done to prevent an insane amount of version fragmentation. A couple of versions don't even work anymore due to changes Roblox made to metatables.
