### ISSUE TITLE
Certain Rthro Avatars have faulty Leg IK

### ISSUE THREAD

**Issue by WhiteOutRBLX** [TheNexusAvenger/Nexus-VR-Character-Model#22]
Tested on the Oculus Quest 2, Headset and Two Controllers.

From what I tested this happens in every game with the Nexus Character Model.
The characters legs are folded up and stay like that no matter what I do. This issue seems to only happen with the new Rthro Avatars: "Kayden", "Devin", "Parker", "Glenn", "Charlie", "Peyton", "Cameron", "Riley".

**Comment by TheNexusAvenger** [comment]
Related to https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/issues/9?

**Comment by WhiteOutRBLX** [comment]
Not, sure. I will try to test this with the newest version of the model soon.

**Comment by TheNexusAvenger** [comment]
Closing with #9.
