### ISSUE TITLE
Movement Issue

### ISSUE THREAD

**Issue by MoxiUAE** [TheNexusAvenger/Nexus-VR-Character-Model#23]
@TheNexusAvenger 

I hope this message finds you well. I recently downloaded your VR script for Roblox and have been enjoying using it. However, I've noticed an issue with the movement controls that's preventing VR players from being able to move their hands and themselves properly. Specifically, : https://streamable.com/6abme9 . ( **_The Video Expires in One Day_** )

I wanted to bring this to your attention as I think it's an important issue that could be impacting the experience of many players. I would be happy to provide any additional information or screenshots to help you diagnose and address the issue.

Thank you for your time and attention to this matter.

**Comment by TheNexusAvenger** [comment]
I don't have any idea what is going on there. I have a feeling it is game-specific, but not sure.
At the moment, [I won't be looking into this](https://thenexusavenger.io/article/28/ending-my-contributions-to-nexus-vr-character-model). Pull requests are open for solutions.

**Comment by TheNexusAvenger** [comment]
May be resolved with version 2.7.0, but it may still be game-specific.
