### ISSUE TITLE
How I can get VR player camera?

### ISSUE THREAD

**Issue by Pickramag** [TheNexusAvenger/Nexus-VR-Character-Model#24]
How I can get VR player camera? For Example how I can equalize Camera.CFrame = part.CFrame?

**Comment by TheNexusAvenger** [comment]
I assume you mean to get the VR camera CFrame? Use `Workspace.CurrentCamera:GetRenderCFrame()`. Applies to all VR and non-VR systems.

**Comment by Pickramag** [comment]
I use this to move Camera:

local Camera = workspace.CurrentCamera
Camera.CameraType = Enum.CameraType.Scriptable
Camera:GetRenderCFrame()
local pos = Vector3.new(0, 10, 0)
local lookAt = Vector3.new(10, 0, 0)
local CameraCFrame = CFrame.new(pos,lookAt)
workspace.CurrentCamera.CFrame = CameraCFrame

But this didn't work. And this is in localscript

**Comment by TheNexusAvenger** [comment]
Why do you want to do that? Nexus VR Character Model manages the camera for you.

**Comment by Pickramag** [comment]
I want move Camera to Jumpscare instead teleport player. Or how I can manage Nexus VR Character Model?

**Comment by TheNexusAvenger** [comment]
That use case isn't supported at the moment. The camera is always tied to the player with no supported way to disable it.

**Comment by Pickramag** [comment]
ok..
