### ISSUE TITLE
Replace Foot Planter (Bug Bounty)

### ISSUE THREAD

**Issue by TheNexusAvenger** [TheNexusAvenger/Nexus-VR-Character-Model#30]
The [current code for the foot planter](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/FootPlanter.lua) is complicated and produces bad-looking results. I want it replaced with a better-looking version that produces more natural results.

There is a **150,000 Robux ($525 in DevEx)** bounty on getting this resolved. It must match the current compatibility with scaled characters, and characters changing sizes.

**Comment by Rondev9** [comment]
Hey @TheNexusAvenger I'm planning to work on this issue, but I find it difficult in setting up the local development as there is no proper documentation, Can you please help me in setting up this project?

**Comment by TheNexusAvenger** [comment]
The project uses [Rojo](https://github.com/rojo-rbx/rojo). Once you clone the repository and *recursively* clone the submodules, you can run `rojo serve` to sync the files into Roblox Studio. Please create a new GitHub Issue for any further questions.

**Comment by TheNexusAvenger** [comment]
I'm closing down the bug bounty now that `VRService.AvatarGestures` is live and is the path forward. Since Nexus VR Character Model will no longer directly control the character, there is no point in having a foot planter.

**Comment by connorkoontz** [comment]
i cant use old ver of nexus vr on roblox i did rojo to roblox not working ple help me work on this
