### ISSUE TITLE
Movement and Camera Controls doesn't work properly with Steam Link VR.

### ISSUE THREAD

**Issue by caisstuff** [TheNexusAvenger/Nexus-VR-Character-Model#32]
Hello, there's currently an issue when using Steam Link VR where the thumbstick movement controls do not work properly.

Movement will drop out, as if i'm just flicking the thumbstick as you will see. This also affects the camera since it will spam it as a result.

I will note I have a Meta Quest 3, I also use the Meta Quest Pro controllers with my Quest 3 most of the time, the problem is able to be replicated on both controllers but for this video example I will use the stock Quest 3 controllers.

This problem is non-existent on Virtual Desktop as you will see, it's not a problem either on Oculus Air Link, it only appears to be an issue with the recently released Steam Link for the Quest. I initially thought it was a ROBLOX issue but looking into it I've narrowed it down to the character module.

I've used the following place to demonstrate this: [VR Drink Demo](https://www.roblox.com/games/14368164180/VR-Drink-Demo)

The following apps were used to test this: [Virtual Desktop](https://www.meta.com/experiences/2017050365004772) and [Steamlink](https://www.meta.com/experiences/5841245619310585)

[Here's the video showing the bug and comparison to how it should work with Virtual Desktop.](https://youtu.be/660OBBJxdZU)

Hope this provides some help with bug fixing, as it makes games using this module unplayable.

_Side note: This is also my first time submitting a bug report, I usually don't do these types of things so sorry if i'm not as professional with it._

**Comment by TheNexusAvenger** [comment]
I'm going to close this with the assumption that this is either an issue with Steam Link or Roblox. Roblox is responsible for input from the various OpenXR runtimes with any issues handled by the platform as opposed to by the developer. There should be no visible difference in the input events when switching OpenXR runtimes like this.

Please re-open this issue if you have confirmation from a Roblox engineer that this is not a Roblox problem.

**Comment by caisstuff** [comment]
> I'm going to close this with the assumption that this is either an issue with Steam Link or Roblox. Roblox is responsible for input from the various OpenXR runtimes with any issues handled by the platform as opposed to by the developer. There should be no visible difference in the input events when switching OpenXR runtimes like this.
> 
> Please re-open this issue if you have confirmation from a Roblox engineer that this is not a Roblox problem.

Hello, this doesn't appear to be an issue normally with places that don't use the module (I should've clarified that more and demonstrated.) But to confirm I will be checking with ROBLOX.

**Comment by TheNexusAvenger** [comment]
I tried this out on a new headset I got and could confirm the issue. It is either a problem with Steam Link or with `GetThumbstickPosition` in [VRInputService](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/State/VRInputService.lua). The logic is a bit complicated to compensate for the Microsoft Mixed Reality. I don't plan to investigate this further, but please re-open it if you are certain that code is the problem. For now, you can get around this by slightly varying your thumbstick position while moving.

**Comment by caisstuff** [comment]
Alright so it's not just me.

Also, a little update; As of writing this I've been reached out by ROBLOX staff responding to my bug report, their name is [Focia19](https://devforum.roblox.com/u/focia19/).

Still awaiting a response from them as they questioned if the issue was still on-going to which I replied yes with updated footage and the repo steps I've taken, they were happy for the ton of information I gave them in my report. (Was slightly worried about that.) So ill either post another response or re-open depending on what they confirm. 

Apologies for taking so long however...😅

Edit: my bug report was approved and is now live on the [dev forum](https://devforum.roblox.com/t/controls-do-not-work-as-expected-over-steamlink-vr-requesting-confirmation-from-an-engineer/2794566).

**Comment by TheNexusAvenger** [comment]
Re-opening this issue because my suspicion about the Windows Mixed Reality workaround was correct. This has been fixed in commit [`3a81310`](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/commit/3a8131038bb66f0dcb46fda7374830c1ec8ed327) and will be released within the next week. **This does mean that Windows Mixed Reality is no longer supported by Nexus VR Character Model**. My hope is the current code works, but it is really hard to test now because the current controller bindings are among the most 🅱️roken I have ever seen for VR bindings - right trigger is button A, and everything else is nothing.

**Comment by TheNexusAvenger** [comment]
Fix released with V.2.9.0. Please re-open if this issue still appears with V.2.9.0.
