### ISSUE TITLE
Should snapping 45° angles be a thing?

### ISSUE THREAD

**Issue by karl-police** [TheNexusAvenger/Nexus-VR-Character-Model#37]
Apparently the joystick only teleports? Not sure if there's a angle snapping to turn around kind of feature.

**Comment by TheNexusAvenger** [comment]
Snap turning should already be a feature in both default controllers.

**Comment by karl-police** [comment]
> Snap turning should already be a feature in both default controllers.

oh my bad, I ment smooth turning

**Comment by TheNexusAvenger** [comment]
Smooth turning is currently not supported. I'm skeptical about the feature due to motion sickness, but feel free to give it a shot and create a PR.
