### ISSUE TITLE
Roblox Smooth turning stops working

### ISSUE THREAD

**Issue by longyi07** [TheNexusAvenger/Nexus-VR-Character-Model#39]
Headset: Metaquest 3
Nexus Version: 2.9.0

Description: without this tool, I can do smooth turning (as opposed to snap turning) in Roblox VR (after turning off the setting -> VR stepped rotation enabled). However after importing this tool, I can only do snap turning.

I can do some investigation myself next week. But let me know if this is a known issue or if I miss anything.
Thanks!

**Comment by TheNexusAvenger** [comment]
Nexus VR Character Model currently does not respect any of the comfort settings. Doing so should be possible by reading [`UserGameSettings.VRSmoothRotationEnabled`](https://create.roblox.com/docs/reference/engine/classes/UserGameSettings#VRSmoothRotationEnabled) and handling the turning differently in [`SmoothLocomotionController`](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/SmoothLocomotionController.lua) and [`TeleportController`](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/TeleportController.lua).

**Comment by longyi07** [comment]
Cool thanks for the context and the pointers!

**Comment by longyi07** [comment]
I have some code changes ready, yet I don't have write access to open up a PR. If this is unintentional and this project is open to contribution, would you like to tweak the repo setting? Thanks

**Comment by longyi07** [comment]
Made a PR, would like to have a CR. Thanks :)

**Comment by TheNexusAvenger** [comment]
Resolved in V.2.10.0.
