### ISSUE TITLE
Interaction with ClickDetectors

### ISSUE THREAD

**Issue by WhiteOutRBLX** [TheNexusAvenger/Nexus-VR-Character-Model#4]
What happened to the interaction with ClickDetectors when the Trigger is pressed? Did it get moved to a new key, has it been scrapped?

Edit: Version 2.1.0

**Comment by TheNexusAvenger** [comment]
ClickDetectors requires 2 things:
- The events need to be abled through Nexus VR Core, which is automatically set up as part of Nexus VR Character Model: https://thenexusavenger.github.io/Nexus-VR-Core/usage/clickdetectors/
- The events need to be connected on the client, not server.

If both of those conditions are met, you aim at the parts and use the trigger of the pointing hand to activate it. The reason this doesn't happen automatically is Roblox does not support ClickDetectors in VR natively and I can't manually call the events from inside Lua code.
