### ISSUE TITLE
No player collision

### ISSUE THREAD

**Issue by NasaBoi1234** [TheNexusAvenger/Nexus-VR-Character-Model#41]
I am making a vr game with this and there is no player collision with walls, I tried it with this removed and there was collision.

**Comment by TheNexusAvenger** [comment]
Nexus VR Character Model does not handle collisions or even physics. That is up to how the Roblox character is set up and how Roblox handles it.

**Comment by NasaBoi1234** [comment]
ah, I found out that on normal mode there is none, but in vr you have to jump before you start geting collision.
