### ISSUE TITLE
Legs disappear whenever Trackers are Calibrated / Trackers don't show up on "Show Trackers" click

### ISSUE THREAD

**Issue by VibeRBLX** [TheNexusAvenger/Nexus-VR-Character-Model#44]
Specifications:
Headset: Oculus Quest 2 (AirLink)
Trackers: 6 SlimeVR Trackers connected to SteamVR

Hello!
Recently wanted to try out new Enigma's integration into Nexus VR, but when I went into the game and clicked Show Trackers - nothing happened, no trackers have appeared. Moreover, upon clicking Calibration - legs have completely disappeared (only in first person, from spectator's view they are just still, like in T-Pose). Of course, enigma-cli.exe was launched this entire time, and the companion plugin is installed. I believe it is due to how raw Enigma is as of right now, but in the twitter's post about enigma releasing Nexus clearly showed everything was working fine. I did hear that only feet trackers are supported, but my main concern here is that **none** of the trackers are showing upon clicking Show Trackers button. 2 tests were conducted, one where I had the entire 6 pack of SlimeVRs turned on, and one where I had only feet trackers on. The results are the same. If there are any logs I can provide, please tell me, I'll reply as fast as I can.
The ONLY error in the console is the one below. It's also worthy to note that my trackers are correctly assigned to Right/Left Feet in SteamVR.

![image](https://github.com/user-attachments/assets/8521cede-5e4b-4b97-b3b8-934ecfc315ff)

**Comment by TheNexusAvenger** [comment]
The stack trace `ServerScriptService.Engima-Plugin` tells me that the plugin is under `ServerScriptService`, which should *not* be done. The plugin only works as a Roblox Studio plugin, which Enigma automatically sets up. Outside of that, it should "just work" as long as the CLI is running, the roles are set (not required for "Show Trackers"), and the Roblox client is focused.

**Comment by VibeRBLX** [comment]
Got a video example of what's happening. I let Enigma set the plugin up, it even told me that the companion app is connected when Studio was in focus, but the issue still persists. No console errors this time. Though, a worrying thing is that the companion app disconnects, is that supposed to happen? Because if yes, then I'm afraid I misunderstood something with installation.

https://github.com/user-attachments/assets/0fb419ea-ffb7-49f9-b76f-39a743dc3b62
https://github.com/user-attachments/assets/a7307252-3897-4af2-9bba-3cd0d518f9ad

**Comment by TheNexusAvenger** [comment]
The stopping happens when the Roblox client is no longer focused. It is a limitation with Enigma that can't be easily addressed.

The videos do show that the communication is working correctly and the tracker roles are correct as well. I don't have SlimeVR trackers to test with, so there is nothing else I can diagnose.

**Comment by VibeRBLX** [comment]
I will close this issue since it appears that it is a SlimeVR-specific issue, but if anyone has SlimeVR and will get it working - please contact me. I will edit this comment as soon as I test Enigma again with additional logging args.

Edit: Seems like the issue is Slime-VR specific after all, trace arg didn't result in any errors thrown out. Moreover, it correctly detected SlimeVR trackers, but I've heard that SlimeVR trackers arent treated as Vive Trackers everywhere, so it might be the case here.
![Screenshot_203](https://github.com/user-attachments/assets/78d4b31e-5f41-41a9-82a6-ae89bd74d426)
