### ISSUE TITLE
Games using latest version of Nexus have broken movement system on Quest 2 and 3

### ISSUE THREAD

**Issue by MagnaOpossum** [TheNexusAvenger/Nexus-VR-Character-Model#45]
I've noticed in many games using the latest version of the Nexus VR Character Model framework (using ctrl + F9 to check) seem to have broken joystick tracking on the Quest 3 and Quest 2. While yes these aren't MY experiences, it's still a prominent issue within any games containing it on these headsets. I don't see it on any games using an older version of Nexus however. I couldn't really pinpoint this when I added it to an experience to test it but when you move the joystick, say, forward, you'll go left, left goes up, so on so forthe.
In games without Nexus VR (aka basic Roblox VR support) however, this is not a problem whatsoever which leads it to an issue with Nexus.
If a developer with more experience in LUA than me, feel free to find it, but this is simply a report I'm providing. I can't pinpoint anything due to my lack of skill in reading code outside python.

**Comment by TheNexusAvenger** [comment]
As of recent versions of Nexus VR Character Model (V.2.10.0 and newer), non-teleport movement controls are handled entirely by Roblox. Issues with this *must* be brought up to Roblox on the developer forum. For long-term compatibility reasons, Nexus VR Character Model will not handle character locomotion.

**Comment by Agarmal** [comment]
> As of recent versions of Nexus VR Character Model (V.2.10.0 and newer), non-teleport movement controls are handled entirely by Roblox. Issues with this _must_ be brought up to Roblox on the developer forum. For long-term compatibility reasons, Nexus VR Character Model will not handle character locomotion.

At this point I believe it doesn't make sense to wait for Roblox to fix it. A patch, even if temporary, would really help. It's impossible to play like this.
