### ISSUE TITLE
How do i use this in normal roblox

### ISSUE THREAD

**Issue by AWanderingToon** [TheNexusAvenger/Nexus-VR-Character-Model#49]
I use a meta quest 2 with link cable, I'm having trouble getting nexus to work.

**Comment by TheNexusAvenger** [comment]
I assume by this that you are a player instead of a game owner. Nexus VR Character Model has to be added to the game to support it (insert the loader into `ServerScriptService`). There is no way to get it working without the game adding support.

**Comment by AWanderingToon** [comment]
ive seen people using it, how so?https://youtu.be/Rc1DU7SSEpw?t=51

**Comment by TheNexusAvenger** [comment]
Assuming a game has it added, all you need to do is join the game in VR. You will want to find external help if you are having issues with playing Roblox in VR as that is on Roblox's end.
