### ISSUE TITLE
Smooth/Tap Turning

### ISSUE THREAD

**Issue by nitrog0d** [TheNexusAvenger/Nexus-VR-Character-Model#5]
Can you work on smooth/tap turning? I play sitting most of the time and I can't really turn due to wires and sensors positions.

**Comment by TheNexusAvenger** [comment]
That functionality already exists for both teleport locomotion (both controllers) as of V.2.0.0 and smooth locomotion (right controller only) as of V.2.1.0. Is there a problem with the current implementation, and on what headset/controllers?

**Comment by nitrog0d** [comment]
I didn't see **turning** in any of the preview videos in your channel, only locomotion
By turning I mean moving your body left and right using the right controller's joystick
Last version I tried was v2.0, and it didn't have that
If you don't know what exactly I'm talking about, I can send you an example from other games like VRChat

**Comment by TheNexusAvenger** [comment]
I realized a while ago I forgot to mention the feature got added, but it is covered in the release notes. If we are talking about the same thing, I actually show it a bit in the latest demo.
https://youtu.be/Y-CuRKAoGac?t=45

**Comment by nitrog0d** [comment]
Oh yeah I was talking about that. I'll try it later on a game. Thank you.
