### ISSUE TITLE
HP Reverb G2 Issues And Support.

### ISSUE THREAD

**Issue by mountainkiller** [TheNexusAvenger/Nexus-VR-Character-Model#6]
Hey, I've recently got my HP Reverb G2 headset (WMR) and I tried playing roblox VR using Nexus VR Character Model it kind of works but kind of doesn't, basically I went into this game that supports it (Club Iris) and I can't rotate with my right controller I've tried numerous binds on SteamVR some are better than others but it looks like most of them are actually for Nexus VR it looks like it meant for the Built in ROBLOX VR feature but anyways I've tried multiple binds and it's very buggy sometimes I have to move my joystick to the right 5 times so I'm pretty sure Nexus VR model doesn't support native WMR or my headset (HP Reverb G2 Motion Controllers) If you need help testing it if you do get to fixing it im glad to help and test.

I've tried this headset on VR Hands not a single issue I know this doesn't use Nexus though but just wanted to mention it I could move normally and rotate so I am guessing this is possible to fix as it works on games I've played on.

I don't know if you still work on the project anymore but I thought you would be the right person to ask to pass it on to someone else as this is a major headset by HP, Valve, Microsoft. and is apart of the WMR headsets.

-Virose

**Comment by mountainkiller** [comment]
one thing I haven't tried is to open the menu which I don't know if that will have anything in there to help me? also I also cant type in roblox vr chat i cant click any of the letters so I literally have to nod and stuff it's a little sad as I can't communicate in text but if this is possible to fix once again I will gladly help.

**Comment by TheNexusAvenger** [comment]
I do validate with Microsoft Mixed Reality to make sure touchpad controls aren't problematic (such as thumbsticks being stuck moved), but the HP Reverb G2 is *very* different. There isn't much I can do with headset-specific problems, especially for ones I don't own with known problems on Roblox's end. All I can suggest is bumping the bug reports if they go stale.

https://devforum.roblox.com/t/hp-reverb-g2-controllers-are-unusable-in-robloxvr/939139
