### ISSUE TITLE
Set time to open menu in NexusVRCharacterModelLoader script

### ISSUE THREAD

**Issue by Pengalu** [TheNexusAvenger/Nexus-VR-Character-Model#7]
It'd be very helpful if we could configure the amount of time you had to hold the menu gesture to open up the menu. Currently, it's difficult to block certain attacks with the melee system I've been working on without opening the menu (Thanks for making it really non-obtrusive though!) It's a very low priority thing to me, but it'd be nice to see it added.

**Comment by TheNexusAvenger** [comment]
This seems like the wrong solution to the problem. If you position that players will get in that opens the menu frequently, you may need to make the wait time super long to make it not open for most but not all players, and the menu indicator will show regardless. Disabling the menu in the configuration is more effective, or changing the gesture so it works as-is but doesn't affect your case.

**Comment by Pengalu** [comment]
In that case, is there any way to open the menu via any other methods, such as binding it to button inputs or a function that can be called?

**Comment by TheNexusAvenger** [comment]
No native way is provided to do this. In any given game with any given headset, I have to assume no buttons aren't being used by the developer, and I can't check.

**Comment by Pengalu** [comment]
I see.
