### ISSUE TITLE
Menu Problems

### ISSUE THREAD

**Issue by mjarduk** [TheNexusAvenger/Nexus-VR-Character-Model#8]
I've used oculus to test the game.
I used the V2 module for convenience's sake.

When attempting to open the menu, the menu appears on the screen for a split second before flying away from the player to an unknown position.

**Comment by TheNexusAvenger** [comment]
Can you clarify which menu?
If it is the Nexus VR Character Model menu, can you provide evidence of this, like a video? I used it about 3 days ago without this issue.
If it is the Roblox menu, I have no way of modifying it and there are known bug reports about it.
https://devforum.roblox.com/t/vr-players-can-only-open-the-game-menu-once-and-never-again/1479194
